# Generated by Django 5.2.1 on 2025-05-16 16:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio_fabricacion', models.PositiveIntegerField()),
                ('km', models.PositiveIntegerField()),
                ('patente', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese una patente válida (formato ABC123 o AB123CD)', regex='^([A-Z]{3}\\d{3}|[a-z]{3}\\d{3}|[a-z]{2}\\d{3}[a-z]{2}|[A-Z]{2}\\d{3}[A-Z]{2})$')])),
                ('categoria', models.CharField(choices=[('E', 'Económico'), ('C', 'Compacto'), ('S', 'Sedán'), ('V', 'SUV'), ('P', 'Pickup')], max_length=1)),
                ('capacidad_pasajeros', models.PositiveIntegerField()),
                ('politica_reembolso', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('precio_por_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='autos/')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
        ),
    ]
