# Generated by Django 5.2.3 on 2025-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('inhabilitado', 'Inhabilitado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
