# Generated by Django 5.2.1 on 2025-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
