# Generated by Django 5.1.7 on 2025-07-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_activo'),
        ('vehiculos', '0002_auto_estado'),
    ]

    operations = [
    ]
