# Generated by Django 5.1.7 on 2025-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_auto_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='patente',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
