# Generated by Django 5.2.3 on 2025-07-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_activo'),
        ('vehiculos', '0002_auto_estado'),
    ]

    operations = [
    ]
