# Generated by Django 5.2 on 2025-05-13 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_auto_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='patente',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese una patente válida (formato ABC123 o AB123CD)', regex='^([A-Z]{3}\\d{3}|[a-z]{3}\\d{3}|[a-z]{2}\\d{3}[a-z]{2}|[A-Z]{2}\\d{3}[A-Z]{2})$')]),
        ),
    ]
