# Generated by Django 5.2.3 on 2025-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_auto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('inhabilitado', 'Inhabilitado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
