# Generated by Django 5.1.7 on 2025-05-08 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_empleadoextra_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoextra',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
