# Generated by Django 5.1.7 on 2025-07-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_empleadoextra_activo_empleadoextra_correo_original'),
        ('usuarios', '0005_alter_usuario_correo'),
    ]

    operations = [
    ]
