# Generated by Django 5.2.3 on 2025-07-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_merge_20250707_1554'),
        ('usuarios', '0006_usuario_activation_token_and_more'),
    ]

    operations = [
    ]
