# Generated by Django 5.2 on 2025-05-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='conductor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
