# Generated by Django 5.1.7 on 2025-05-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_en_tarjeta', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('vencimiento', models.CharField(max_length=5)),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
        ),
    ]
