# Generated by Django 5.2.1 on 2025-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_pagosimulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dni_conductor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
