# Generated by Django 5.1.7 on 2025-05-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_en_tarjeta', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('vencimiento', models.CharField(max_length=5)),
                ('codigo_seguridad', models.CharField(max_length=4)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagosimulado',
            name='codigo_seguridad',
        ),
        migrations.RemoveField(
            model_name='pagosimulado',
            name='nombre_en_tarjeta',
        ),
        migrations.RemoveField(
            model_name='pagosimulado',
            name='numero_tarjeta',
        ),
        migrations.RemoveField(
            model_name='pagosimulado',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='pagosimulado',
            name='tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.tarjeta'),
        ),
    ]
