# Generated by Django 5.1.7 on 2025-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_tarjeta_remove_pagosimulado_codigo_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dni_conductor',
            field=models.CharField(default='', max_length=8),
        ),
    ]
