# Generated by Django 5.2.3 on 2025-07-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_dni_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dias_retraso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='es_devolucion_tardia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='multa_por_retraso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
