# Generated by Django 5.2.4 on 2025-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_reserva_seguro_basico_reserva_seguro_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='conductor_adicional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dni_conductor_adicional',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='reserva',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_conductor_adicional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='silla_bebe',
            field=models.BooleanField(default=False),
        ),
    ]
