# Generated by Django 5.2.4 on 2025-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_reserva_conductor_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_seguro',
            field=models.CharField(blank=True, choices=[('basico', 'Seguro Básico'), ('completo', 'Seguro Completo'), ('premium', 'Seguro Premium')], default='basico', max_length=20, null=True),
        ),
    ]
